CASE: main
ACTION: eval
# ----- Model config -----:
MODEL_NAME: normal_QK_model
ATOM_FEATURES:
  - AtomicNum
  - ChiralTag
  - Hybridization
  - FormalCharge
  - NumImplicitHs
  - ExplicitValence
  - Mass
  - IsAromatic
BOND_FEATURES:
  - BondType
  - Stereo
  - IsAromatic
RESTORE_FILE: /mnt/logs/m2or/mixDiscard_20230428-122803/EC50_random_data/20230428-122918/orphans__keep/quality__screening_weight/mix__concatGraph/normal_QK_model/20230428-140055/ckpts/state_e10.pkl
# ----- Graph config -----:
LINE_GRAPH: false
LINE_GRAPH_MAX_SIZE_MULTIPLIER: 5
SELF_LOOPS: false
# ----- Run config -----:
BATCH_SIZE: 200
LOADER_OUTPUT_TYPE: tf
N_PARTITIONS: 0
PADDING_N_EDGE: 256
PADDING_N_NODE: 128
PYTABLE_FROM_DISK: false
# ----- Train config -----:
LEARNING_RATE: 0.001
LOSS_OPTION: cross_entropy
OPTIMIZATION:
  OPTION: adam_transformer
  WARMUP_STEPS: 6000
  TRANSITION_EPOCHS: 500
# ----- Data config -----:
VALID_CSV_NAME: data_test.csv
BERT_H5FILE: /mnt/Data/m2or/mixDiscard_20230428-122803/PrecomputeProtBERT_CLS/ProtBERT_CLS.h5
DATACASE: m2or/mixDiscard_20230428-122803/EC50_random_data/20230428-122918/orphans__keep/quality__screening_weight/mix__concatGraph
DATA_PARENT_DIR: /mnt/Data
LABEL_COL: Responsive
MOL_COL: _SMILES
SEQ_COL: null
SEQ_ID_COL: seq_id
VALID_WEIGHT_COL: null
