CASE: BERT_GNN
ACTION: predict_single
# ----- Model config -----:
MODEL_NAME: normal_QK_model
ATOM_FEATURES:
  - AtomicNum
  - ChiralTag
  - Hybridization
  - FormalCharge
  - NumImplicitHs
  - ExplicitValence
  - Mass
  - IsAromatic
BOND_FEATURES:
  - BondType
  - Stereo
  - IsAromatic
RESTORE_FILE: /mnt/logs/m2or/mixDiscard_20230428-122803/EC50_random_data/20230428-122918/orphans__keep/quality__screening_weight/mix__concatGraph/normal_QK_model/20230428-140055/ckpts/state_e10.pkl
# ----- Graph config -----: 
LINE_GRAPH: false
LINE_GRAPH_MAX_SIZE_MULTIPLIER: 5
SELF_LOOPS: false
# ----- Run config -----:
BATCH_SIZE: 200
LOADER_OUTPUT_TYPE: jax
N_PARTITIONS: 0
PADDING_N_EDGE: 256
PADDING_N_NODE: 128
RETURN_INTERMEDIATES: true
# ----- Train config -----:
LEARNING_RATE: 0.001
OPTIMIZATION:
  OPTION: adam_transformer
  WARMUP_STEPS: 6000
  TRANSITION_EPOCHS: 500
# ----- Logging config -----:
LOGGING_PARENT_DIR: /mnt/Predictions/pairs/_single
# ----- Input config -----:
SEQ_ID: OR1A1
MUTATED_SEQUENCE: MRENNQSSTLEFILLGVTGQQEQEDFFYILFLFIYPITLIGNLLIVLAICSDVRLHNPMYFLLANLSLVDIFFSSVTIPKMLANHLLGSKSISFGGCLTQMYFMIALGNTDSYILAAMAYDRAVAISRPLHYTTIMSPRSCIWLIAGSWVIGNANALPHTLLTASLSFCGNQEVANFYCDITPLLKLSCSDIHFHVKMMYLGVGIFSVPLLCIIVSYIRVFSTVFQVPSTKGVLKAFSTCGSHLTVVSLYYGTVMGTYFRPLTNYSLKDAVITVMYTAVTPMLNPFIYSLRNRDMKAALRKLFNKRISS
MOL_ID: ULDHMXUKGWMISQ-SECBINFHSA-N_R_carvone
SMILES: CC1=CC[C@H](CC1=O)C(=C)C